site_name: Drill Dungeon Game





theme:
    name: null
    custom_dir: mkdocs_windmill_dark

    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true


nav:
    - Home: index.md
    



markdown_extensions:
    - toc:
        permalink: '#'

extra:
    version: 0.1.4